/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template
 */
package Hotel;

/**
 *
 * @author ricardo
 */
public class Hospede {
    
    private String email;
    private String nome;
    private String cpf;
    private String numero;
    private String endereco;
    
    public Hospede(String email, String nome, String cpf, String numero, String endereco) {
        
        this.email = email;
        this.nome = nome;
        this.cpf = cpf;
        this.numero = numero;
        this.endereco = endereco;
        
       
    }
    
}
